export const SoundtracksListCaptionKeys = [
  '№',
  'sections.playlist.caption.soundtrack',
  'sections.playlist.caption.time',
  'sections.playlist.caption.album',
  'sections.playlist.caption.genre',
  'sections.playlist.caption.author',
]

export const SoundtracksList = [
  {
    id: 1,
    soundtrackName: 'In Love With A Ghost',
    time: '2:46',
    album: 'Unknown',
    genre: 'Electronic',
    author: 'AX.EL',
  },
  {
    id: 2,
    soundtrackName: 'In Love With A Ghost',
    time: '2:46',
    album: 'Unknown',
    genre: 'Electronic',
    author: 'AX.EL',
  },
  {
    id: 3,
    soundtrackName: 'In Love With A Ghost',
    time: '2:46',
    album: 'Unknown',
    genre: 'Electronic',
    author: 'AX.EL',
  },
  {
    id: 4,
    soundtrackName: 'In Love With A Ghost',
    time: '2:46',
    album: 'Unknown',
    genre: 'Electronic',
    author: 'AX.EL',
  },
  {
    id: 5,
    soundtrackName: 'In Love With A Ghost',
    time: '2:46',
    album: 'Unknown',
    genre: 'Electronic',
    author: 'AX.EL',
  },
  {
    id: 6,
    soundtrackName: 'In Love With A Ghost',
    time: '2:46',
    album: 'Unknown',
    genre: 'Electronic',
    author: 'AX.EL',
  },
  {
    id: 7,
    soundtrackName: 'In Love With A Ghost',
    time: '2:46',
    album: 'Unknown',
    genre: 'Electronic',
    author: 'AX.EL',
  },
  {
    id: 8,
    soundtrackName: 'In Love With A Ghost',
    time: '2:46',
    album: 'Unknown',
    genre: 'Electronic',
    author: 'AX.EL',
  },
  {
    id: 9,
    soundtrackName: 'In Love With A Ghost',
    time: '2:46',
    album: 'Unknown',
    genre: 'Electronic',
    author: 'AX.EL',
  },
  {
    id: 10,
    soundtrackName: 'In Love With A Ghost',
    time: '2:46',
    album: 'Unknown',
    genre: 'Electronic',
    author: 'AX.EL',
  },
]
