export { PlayIcon } from './play.icon'
export { SwitchIcon } from './switch-icon/switch.icon'
export { ShuffleIcon } from './shuffle.icon'
export { LoopIcon } from './loop.icon'
export { VolumeIcon } from './volume.icon'
